version: '3'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ~/.n8n:/home/node/.n8n
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
    command: >
      /bin/sh -c "
        cd /usr/local/lib/node_modules/n8n &&
        wget https://github.com/yourusername/n8n-nodes-twenty/releases/latest/download/n8n-nodes-twenty.tgz &&
        npm install n8n-nodes-twenty.tgz &&
        n8n start
      "
